# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stackify-agent.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "stackify.LogGroup" do
    optional :environment, :string, 1
    optional :server_name, :string, 2
    optional :application_name, :string, 3
    optional :application_location, :string, 4
    optional :logger, :string, 5
    optional :platform, :string, 6
    repeated :logs, :message, 7, "stackify.LogGroup.Log"
    optional :container, :message, 8, "stackify.LogGroup.Container"
    optional :kubernetes, :message, 9, "stackify.LogGroup.Kubernetes"
  end
  add_message "stackify.LogGroup.Container" do
    optional :image_id, :string, 1
    optional :image_repository, :string, 2
    optional :image_tag, :string, 3
    optional :container_id, :string, 4
    optional :container_name, :string, 5
  end
  add_message "stackify.LogGroup.Kubernetes" do
    optional :pod_name, :string, 1
    optional :pod_namespace, :string, 2
    optional :cluster_name, :string, 3
  end
  add_message "stackify.LogGroup.Log" do
    optional :message, :string, 1
    optional :data, :string, 2
    optional :thread_name, :string, 3
    optional :date_millis, :int64, 4
    optional :level, :string, 5
    optional :transaction_id, :string, 6
    optional :source_method, :string, 7
    optional :source_line, :int32, 8
    optional :id, :string, 9
    repeated :tags, :string, 10
    optional :error, :message, 11, "stackify.LogGroup.Log.Error"
  end
  add_message "stackify.LogGroup.Log.Error" do
    optional :environment_detail, :message, 1, "stackify.LogGroup.Log.Error.EnvironmentDetail"
    optional :date_millis, :int64, 2
    optional :error_item, :message, 3, "stackify.LogGroup.Log.Error.ErrorItem"
    optional :web_request_detail, :message, 4, "stackify.LogGroup.Log.Error.WebRequestDetail"
    map :server_variables, :string, :string, 5
    optional :customer_name, :string, 6
    optional :username, :string, 7
  end
  add_message "stackify.LogGroup.Log.Error.EnvironmentDetail" do
    optional :device_name, :string, 1
    optional :application_name, :string, 2
    optional :application_location, :string, 3
    optional :configured_application_name, :string, 4
    optional :configured_environment_name, :string, 5
  end
  add_message "stackify.LogGroup.Log.Error.ErrorItem" do
    optional :message, :string, 1
    optional :error_type, :string, 2
    optional :error_type_code, :string, 3
    map :data, :string, :string, 4
    optional :source_method, :string, 5
    repeated :stacktrace, :message, 6, "stackify.LogGroup.Log.Error.ErrorItem.TraceFrame"
    optional :inner_error, :message, 7, "stackify.LogGroup.Log.Error.ErrorItem"
  end
  add_message "stackify.LogGroup.Log.Error.ErrorItem.TraceFrame" do
    optional :code_filename, :string, 1
    optional :line_number, :int32, 2
    optional :method, :string, 3
  end
  add_message "stackify.LogGroup.Log.Error.WebRequestDetail" do
    optional :user_ip_address, :string, 1
    optional :http_method, :string, 2
    optional :request_protocol, :string, 3
    optional :request_url, :string, 4
    optional :request_url_root, :string, 5
    optional :referral_url, :string, 6
    map :headers, :string, :string, 7
    map :cookies, :string, :string, 8
    map :querystring, :string, :string, 9
    map :post_data, :string, :string, 10
    map :session_data, :string, :string, 11
    optional :post_data_raw, :string, 12
    optional :mvc_action, :string, 13
    optional :mvc_controller, :string, 14
    optional :mvc_area, :string, 15
  end
end

module Stackify
  LogGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup").msgclass
  LogGroup::Container = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Container").msgclass
  LogGroup::Kubernetes = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Kubernetes").msgclass
  LogGroup::Log = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log").msgclass
  LogGroup::Log::Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log.Error").msgclass
  LogGroup::Log::Error::EnvironmentDetail = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log.Error.EnvironmentDetail").msgclass
  LogGroup::Log::Error::ErrorItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log.Error.ErrorItem").msgclass
  LogGroup::Log::Error::ErrorItem::TraceFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log.Error.ErrorItem.TraceFrame").msgclass
  LogGroup::Log::Error::WebRequestDetail = Google::Protobuf::DescriptorPool.generated_pool.lookup("stackify.LogGroup.Log.Error.WebRequestDetail").msgclass
end
